name: Cleanup AWS Strapi Resources

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'destroy' to confirm cleanup"
        required: true
        default: "cancel"

jobs:
  cleanup:
    if: github.event.inputs.confirm == 'destroy'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false

    - name: Verify Resources Destroyed
      run: |
        if [ $(terraform state list | wc -l) -eq 0 ]; then
          echo "All resources destroyed successfully"
        else
          echo "Some resources still exist"
          terraform state list
          exit 1
        fi