name: Cleanup AWS Resources

description: "Manual workflow to destroy AWS infrastructure when no longer needed."

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Destroy
      working-directory: ./terraform
      run: terraform destroy -auto-approve