name: Deploy Strapi to AWS ECS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: strapi-cluster
  ECS_SERVICE: strapi-service
  CONTAINER_NAME: strapi
  IMAGE: strapi/strapi:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }} 

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2 
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false

    - name: Get ALB DNS name
      id: alb-dns
      run: echo "url=$(terraform output -raw app_url)" >> $GITHUB_OUTPUT

    - name: Print Application URL
      run: echo "Application deployed at: ${{ steps.alb-dns.outputs.url }}"