name: Deploy to EC2 with Terraform

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Clean Terraform State (Optional - for fresh deployments)
        run: |
          rm -f terraform.tfstate terraform.tfstate.backup
          rm -rf .terraform
        working-directory: ./Terraform

      - name: Terraform Init
        run: terraform init
        working-directory: ./Terraform

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="key_name=ayushkey" \
            -var="docker_image=ayusht45cyber/mystrapici" \
            -var="image_tag=${{ github.event.inputs.image_tag }}"
        working-directory: ./Terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="key_name=ayushkey" \
            -var="docker_image=ayusht45cyber/mystrapici" \
            -var="image_tag=${{ github.event.inputs.image_tag }}"
        working-directory: ./Terraform
