name: Deploy to EC2 with Terraform

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Terraform

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: |
        terraform plan \
          -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
          -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}" \
          -var="key_name=ayushkey" \
          -var="docker_image=ayusht45cyber/mystrapici" \
          -var="image_tag=${{ github.event.inputs.image_tag }}"

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
          -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}" \
          -var="key_name=ayushkey" \
          -var="docker_image=ayusht45cyber/mystrapici" \
          -var="image_tag=${{ github.event.inputs.image_tag }}"
